apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-wp
spec:
  storageClassName: nfs-storageclass # must be the same as storage-class
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 4Gi
